version: "3.8"
services:
  ##### Auth #####
  frontend:
    container_name: fafago-fronted
      image: 'fafagoauth/frontend:dev'
      environment:
        - NODE_ENV=production
        - PORT=80
        - REACT_APP_ENDPOINT_API_AUTH=${DOMAIN_PREFIX_AUTH}${DOMAIN_SUFFIX} 
        - REACT_APP_ENDPOINT_API_PRODUCTS=${DOMAIN_PREFIX_PRODUCTS}${DOMAIN_SUFFIX}
        - REACT_APP_ENDPOINT_API_REVIEWS=${DOMAIN_PREFIX_REVIEWS}${DOMAIN_SUFFIX} 
        - REACT_APP_ENDPOINT_API_MESSENGER=${DOMAIN_PREFIX_MESSENGER}${DOMAIN_SUFFIX}
      networks:
        fafago_network:
          aliases:
            - ${DOMAIN_PREFIX_FRONTEND}${DOMAIN_SUFFIX}
      mem_limit: 600m
      restart: 'unless-stopped'
  auth:
    container_name: fafago-auth-api
    image: 'fafagoauth/auth:test'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_HOSTNAME=${AUTH_MONGO_HOSTNAME}${DOMAIN_SUFFIX}
      - MONGO_PORT=${AUTH_MONGO_PORT}
      - MONGO_DB=${AUTH_MONGO_DB}
      - REDIS_HOSTNAME=${AUTH_REDIS_HOSTNAME}${DOMAIN_SUFFIX}
      - REDIS_PORT=${AUTH_REDIS_PORT}
      - PRODUCTS_HOSTNAME=${DOMAIN_PREFIX_PRODUCTS}${DOMAIN_SUFFIX}
      - REVIEWS_HOSTNAME=${DOMAIN_PREFIX_REVIEWS}${DOMAIN_SUFFIX}  
      - CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
    networks:
      auth_network:
      fafago_network:
        aliases:
          - ${DOMAIN_PREFIX_AUTH}${DOMAIN_SUFFIX}
    mem_limit: 400m
    restart: 'unless-stopped'
  auth_mongo:
    container_name: fafago-auth-mongo
    image: 'mongo'
    networks:
      auth_network:
        aliases:
          - ${AUTH_MONGO_HOSTNAME}${DOMAIN_SUFFIX}
    volumes:
      - 'auth_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  auth_redis:
    container_name: fafago-auth-redis
    image: 'redis'
    networks:
      auth_network:
        aliases:
          - ${AUTH_REDIS_HOSTNAME}${DOMAIN_SUFFIX}
    mem_limit: 600m
    restart: "unless-stopped"
  ##### Products #####
  products:
    container_name: fafago-products-api
    image: 'fafagoproducts/productsapi:latest'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_PORT=${PRODUCTS_MONGO_PORT}
      - MONGO_DB=${PRODUCTS_MONGO_DB}
      - HOST_AUTH=${DOMAIN_PREFIX_AUTH}${DOMAIN_SUFFIX}
      - HOST_REVIEWS=${DOMAIN_PREFIX_REVIEWS}${DOMAIN_SUFFIX}
    networks:
      products_network:
      fafago_network:
        aliases:
          - ${DOMAIN_PREFIX_PRODUCTS}${DOMAIN_SUFFIX}
    mem_limit: 400m
    restart: 'unless-stopped'
  products_mongo:
    container_name: fafago-products-mongo
    image: 'mongo'
    networks:
      products_network:
        aliases:
          - ${PRODUCTS_MONGO_HOSTNAME}${DOMAIN_SUFFIX}
    volumes:
      - 'products_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  ##### Reviews #####
  reviews:
    container_name: fafago-reviews-api
    image: fafagoreviews/reviews:dev
    networks:
      reviews_network:
      fafago_network:
        aliases:
          - ${DOMAIN_PREFIX_REVIEWS}${DOMAIN_SUFFIX}
    environment:
      - PORT=80
      - DB_SSL=${REVIEWS_DB_SSL}
      - DB_AUTH=${REVIEWS_DB_AUTH}
      - DB_SERVER=${REVIEWS_MONGO_HOSTNAME}${DOMAIN_SUFFIX}
      - DB_PORT=${REVIEWS_DB_PORT}
      - DB_NAME=${REVIEWS_DB_NAME}
      - ENVIRONMENT=${REVIEWS_ENVIRONMENT}
      - AUTH_URL=${DOMAIN_PREFIX_AUTH}${DOMAIN_SUFFIX}
      - API_KEY_DEEPAI=${API_KEY_DEEPAI}
    mem_limit: 400m
    restart: 'unless-stopped'
  reviews_mongo:
    container_name: fafago-reviews-mongo
    image: mongo
    networks:
      reviews_network:
        aliases:
          - ${REVIEWS_MONGO_HOSTNAME}${DOMAIN_SUFFIX}
    volumes:
      - 'reviews_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  ##### Messenger #####
  messenger:
    container_name: fafago-messenger-api
    image: fafagomessenger/messenger:test
    environment:
      - NODE_ENV=production
      - APP_PORT=80
      - REDIS_HOST=${MESSENGER_REDIS_HOSTNAME}${DOMAIN_SUFFIX}
      - REDIS_PORT=${MESSENGER_REDIS_PORT}
      - HOST_AUTH=${DOMAIN_PREFIX_AUTH}${DOMAIN_SUFFIX}
      - HOST_PRODUCT=${DOMAIN_PREFIX_PRODUCTS}${DOMAIN_SUFFIX}
    networks:
      messenger_network:
      fafago_network:
        aliases:
          - ${DOMAIN_PREFIX_MESSENGER}${DOMAIN_SUFFIX}
    mem_limit: 400m
    restart: 'unless-stopped'
  messenger_redis:
    container_name: fafago-messenger-redis
    image: redis:6.0.9-alpine
    networks:
      messenger_network:
        aliases:
          - ${MESSENGER_REDIS_HOSTNAME}${DOMAIN_SUFFIX}
    volumes:
      - 'messenger_redis_volume:/data' 
    mem_limit: 600m 
    restart: 'unless-stopped'

networks:
  fafago_network: null
  auth_network: null
  products_network: null
  reviews_network: null
  messenger_network: null

volumes:
  auth_mongo_volume: null
  products_mongo_volume: null
  reviews_mongo_volume: null
  messenger_redis_volume: null
