version: "3.8"

services:
  ##### Auth #####
  auth:
    container_name: fafago-auth-api
    image: 'fafagoauth/auth:test'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_HOSTNAME=${MONGO_HOSTNAME}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - PRODUCTS_HOSTNAME=${PRODUCTS_HOSTNAME}
      - REVIEWS_HOSTNAME${REVIEWS_HOSTNAME}
      - CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
    ports:
      - "80:80"
    networks:
      - auth_network
      fafago_network:
        aliases:
          - auth.fafago
    mem_limit: 400m
    restart: 'unless-stopped'
  auth_mongo:
    container_name: fafago-auth-mongo
    image: 'mongo'
    networks:
      auth_network:
        aliases:
          - ${MONGO_HOSTNAME}
    volumes:
      - 'auth_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  auth_redis:
    container_name: fafago-auth-redis
    image: 'redis'
    networks:
      auth_network:
        aliases:
          - ${REDIS_HOSTNAME}
    mem_limit: 600m
    restart: "unless-stopped"
  ##### Products #####
  products:
    container_name: fafago-products-api
    image: 'fafagoproducts/productsapi:latest'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "80:80"
    networks:
      - products_network
      fafago_network:
        aliases:
          - products.fafago
    mem_limit: 400m
    restart: 'unless-stopped'
  products_mongo:
    container_name: fafago-products-mongo
    image: 'mongo'
    networks:
      products_network:
        aliases:
          - mongoproducts
    volumes:
      - 'products_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  ##### Reviews #####
  reviews:
    container_name: fafago-reviews-api
    image: fafagoreviews/reviews:dev
    networks:
      - reviews_network
      fafago_network:
        aliases:
          - reviews.fafago
    environment:
      - PORT=80
      - DB_SSL=${DB_SSL}
      - DB_AUTH=${DB_AUTH}
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_URL=${AUTH_URL}
      - API_KEY_DEEPAI=${API_KEY_DEEPAI}
    mem_limit: 400m
    restart: 'unless-stopped'
  reviews_mongo:
    container_name: fafago-reviews-mongo
    image: mongo
    networks:
      reviews_network:
        aliases:
          - mongo_reviews
    volumes:
      - 'reviews_mongo_volume:/data/db'
    mem_limit: 600m
    restart: 'unless-stopped'
  ##### Messenger #####
  messenger:
    container_name: fafago-messenger-api
    image: fafagomessenger/messenger:test
    environment:
      - NODE_ENV=production
      - APP_PORT=80
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HOST_AUTH=${HOST_AUTH}
      - HOST_PRODUCT=${HOST_PRODUCT}
    networks:
      - messenger_network
      fafago_network:
        aliases:
          - messenger.fafago
    mem_limit: 400m
    restart: 'unless-stopped'
  messenger_redis:
    container_name: fafago-messenger-redis
    image: redis:6.0.9-alpine
    networks:
      messenger_network:
        aliases:
          - mongo_reviews
    volumes:
      - 'messenger_redis_volume:/data' 
    mem_limit: 600m 
    restart: 'unless-stopped'

networks:
  auth_network: null
  products_network: null
  reviews_network: null
  messenger_network: null
  fafago_network: null

volumes:
  auth_mongo_volume: null
  products_mongo_volume: null
  reviews_mongo_volume: null
  messenger_redis_volume: null
