name: Node.js CI

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop]

jobs:
  test:
    name: Install mocha and run tests (docker-compose up, mocha tests and docker-compose down)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: ls tests 0
      run: ls tests
    - name: Secret to env
      run: echo API_KEY_DEEPAI=${{secrets.API_KEY_DEEPAI}} >> tests/.env
    - name: Secret to env
      run: echo HOLA=123 >> tests/.env
    - name: ls tests
      run: ls tests
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm ci
    - name: Run tests
      run: npm run test
      env:
        CI: true
